name: Test CI

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Print Hello
      run: echo "Hello from GitHub Actions 👋"
